CREATE SCHEMA IF NOT EXISTS alphasolutions DEFAULT CHARACTER SET utf8;
USE alphasolutions; 
DROP TABLE IF EXISTS names;
CREATE TABLE names (
	nameString VARCHAR(255), 
    nameID INT PRIMARY KEY AUTO_INCREMENT
    );
