use alphasolutions;
INSERT INTO names (nameString) VALUE("Carl Harlang");
INSERT INTO names (nameString) VALUE("Sadek Alsukafi");
INSERT INTO names(nameString) VALUE("Tore Simonsen");
INSERT INTO names(nameString) VALUE("Simone Gottbrecht");
INSERT INTO positions(posID,posName) VALUE (1,"manager");
INSERT INTO positions(posID,posName) VALUE (2, "developer");
INSERT INTO employee(empName) VALUE ("Sadek");
INSERT INTO employee(empName) VALUE("Simone");
INSERT INTO project(projectName, managerEmployee_ID) VALUE ("projectAlpha", 2);
INSERT INTO project(projectName, managerEmployee_ID) VALUE ("projectAlphaa2", 2);
INSERT INTO tasks(taskName, taskDescription, cost, totalEstimatedTime, project_ID) VALUE ("oprette tasks","Oprette tasks så det kan sees i webappen", 100, 200, 1);
INSERT INTO tasks(taskName, taskDescription , cost, totalEstimatedTime, project_ID) VALUE ("oprette Subtasks", "Oprette SUBtasks så det kan sees i webappen",50, 100, 2);
INSERT INTO tasks(taskName, taskDescription , cost, totalEstimatedTime, project_ID, superTask) VALUE ("Deadlines", "Tjek at man kan lave deadlines",1, 60, 1, 1);
INSERT INTO tasks(taskName, taskDescription , cost, totalEstimatedTime, project_ID, superTask) VALUE ("Lav kaffe", "100% den vigtigeste opgave",69, 420, 2, 2);
INSERT INTO tasks(taskName, taskDescription , cost, totalEstimatedTime, project_ID, superTask) VALUE ("Husk at holde pause", "Optimer arbejdstid ved at holde pause <3",1200000, 56532, 1, 2);
INSERT INTO worksOn(empID,taskID) VALUE (2, 1);
INSERT INTO worksOn(empID,taskID) VALUE (1, 2);
INSERT INTO deadlines (deadline_time, taskID) VALUES ('2023-05-12 12:00:00', 1);
INSERT INTO deadlines (deadline_time, taskID) VALUES ('2023-10-07 11:48:24', 2);
INSERT INTO deadlines (deadline_time, taskID) VALUES ('2023-05-31 12:00:00', 3);
INSERT INTO deadlines (deadline_time, taskID) VALUES ('2021-05-08 10:53:00', 4);
INSERT INTO deadlines (deadline_time, taskID) VALUES ('2022-05-12 10:55:00', 5);
COMMIT;