name: Docker Build

on:
  workflow_dispatch:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Build Docker image
        run:
          docker build -t alphasolutions .
      - name: Run Docker image
        run:
          docker run -e MYSQL_ROOT_PASSWORD=root alphasolutions
