name: Render Deploy Test
on:
  workflow_dispatch:
  pull_request:
    branches: [master]
jobs:
  test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build and deploy to Render
        env:
          RENDER_EMAIL: ${{ secrets.RENDER_EMAIL }}
          RENDER_PASSWORD: ${{ secrets.RENDER_PASSWORD }}
        run: |
          mvn package -DskipTests=true
          render deploy --branch=$GITHUB_HEAD_REF -- --spring.profiles.active=prod